name:                blog
version:             0.1.0.0
github:              "saifulbkhan/saifulbkhan.github.io"
license:             BSD3
author:              "Saiful B. Khan"
maintainer:          "saifulbkhan@gmail.com"
copyright:           "2019 Saiful"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Blog generator and source files

executables:
  blog:
    main:                Main.hs
    source-dirs:         generateblog
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - aeson
    - lens-aeson
    - lens
    - pandoc
    - text
    - binary
    - bytestring
    - containers
    - mustache
    - time
  create-post:
    main:                Main.hs
    source-dirs:         createpost
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - aeson
    - yaml
    - text
    - bytestring
    - containers
    - time
    - filepath
    - utf8-string
